### ISSUE TITLE
window.open is not a function in FF

### ISSUE THREAD

**Issue by greeven** [PixelsCommander/Download-File-JS#2]
Hi,
your Plugin works fine in Chrome but in FF (25.0.1) i get the error "TypeError: window.open ist not a function" (download.js:27).

I can't figure out why and can imagine that this might be a noob-issue.

Can you think of something that could cause FF to throw that error? Of course i can add more information and code, if that's necessary.

**Comment by PixelsCommander** [comment]
Hi

What version of FF do you use?

2013/12/13 greeven notifications@github.com

**Comment by PixelsCommander** [comment]
I suppose that it can be code - specific issue. Probably you redefined one
of functions or objects being used.

If you would send me project files I be able to tell more.

2013/12/13 Denis Radin denis.radin@gmail.com

**Comment by greeven** [comment]
Thanks for the fast response!

I fixed it. Problem was - as usual - me, the coder. I'd already stumbled upon a blog-entry saying "you might have declared 'open' in your code".

So I checked my js-files and figured: nope. haven't declared it.

But silly me forgot a small js-file where I - oh wonder - declared a variable called: open. -.-

So all is fine know! Thx!
